---
- name: Setup cluster hosts
  hosts: cluster
  tasks:
    - name: Update cache and upgrade system
      apt: update_cache=yes upgrade=dist

    - name: Install bridge-utils
      apt: name=bridge-utils

    - name: Ensure container network interface
      interfaces: >
        name=eth2
        iface_type=static
        address={{tunnel_ip}}
        force=true

    - name: Add vxlan42 interface
      interfaces: >-
        name=vxlan42
        iface_type=manual
        updown="pre-up ip link add vxlan42 type vxlan id 42 group 239.0.0.42 dev eth2 || true","up ip link set $IFACE up","down ip link set $IFACE down","post-down ip link del vxlan42 || true"
        force=true

    - name: Add br-mgmt interface
      interfaces: >-
        name=br-mgmt
        iface_type=static
        address={{container_ip}}
        updown="bridge_ports vxlan42"
        force=true

    - name: Reboot
      command: reboot

    - name: Wait for SSH to come back
      local_action: wait_for port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH delay=10
